version: 2
jobs:
  unit-testing:
    working_directory: ~/src/github.com/affectv/samesite-cookie-support
    docker:
      - image: golang:1.13-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-go-dependencies-{{ checksum "go.mod" }}
      - run:
          name: Install dependencies
          command: |
            go mod tidy
      - run:
          name: Running Unit Tests
          command: |
            ginkgo -cover -race -outputdir=./ ./...
      - run:
          name: Generate code coverage
          command: |
            echo "mode: set" > coverage.out
            cat *.coverprofile | grep -v mode: | sort -r | awk '{if($1 != last) {print $0;last=$1}}' >> coverage.out
            go tool cover -html=coverage.out -o coverage.html
      - store_artifacts:
          path: coverage.html
          destination: coverage
      - save_cache:
          paths:
            - "/go/pkg/mod"
          key: v1-go-dependencies-{{ checksum "go.mod" }}

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - unit-testing:
          context: org-global
